### ISSUE TITLE
Packages shouldn't be allowed to depend on themself

### ISSUE THREAD

**Issue by jmackie** [ditto-lang/ditto#116]
Given the following `ditto.toml`:

```toml
name = "example"
dependencies = ["example"]

[[package-set.extends]]
url = "some-package-set"
sha256 = "some-sha256"
```

In a world where this `example` package exists in the final `package-set`, having a self-dependency like this shouldn't be allowed.
