### ISSUE TITLE
Compile-time environment variables

### ISSUE THREAD

**Issue by jmackie** [ditto-lang/ditto#131]
Given the following section in the `ditto.toml`

```toml
[env]
FOO = "foo"
BAR = ""
# Use the following form to inherit from the current process 
# (only applies when the current package is the entrypoint)
BAZ = { inherit = true, default = "BAZ" }
```

You can then reference them using python-style magic variable syntax:

```
foo : String = __FOO__
bar_is_set : Bool = __BAR__ === ""
baz : String = __BAZ__
```
